#!/bin/bash
#
# Mod by Sakariya Misayalong
# ==================================================
clear
rm -f install
scrip="http://smile-vpn.net/scrip/scrip_350/install/pritunl"
# go to root
cd

# Install Pritunl
#!/bin/bash
sudo tee -a /etc/yum.repos.d/mongodb-org-3.4.repo << EOF
[mongodb-org-3.4]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/7/mongodb-org/3.4/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-3.4.asc
EOF

sudo tee -a /etc/yum.repos.d/pritunl.repo << EOF
[pritunl]
name=Pritunl Repository
baseurl=https://repo.pritunl.com/stable/yum/centos/7/
gpgcheck=1
enabled=1
EOF

sudo yum -y install epel-release
gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A
gpg --armor --export 7568D9BB55FF9E5287D586017AE645C0CF8E292A > key.tmp; sudo rpm --import key.tmp; rm -f key.tmp
sudo yum -y install pritunl mongodb-org
sudo systemctl start mongod pritunl
sudo systemctl enable mongod pritunl


# Install Squid
yum -y install squid
cp /etc/squid/squid.conf /etc/squid/squid.conf.orig
wget -q -O /etc/squid/squid.conf "$scrip/squid.conf" 
MYIP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | grep -v '192.168'`;
sed -i s/xxxxxxxxx/$MYIP/g /etc/squid/squid.conf;
service squid restart


# Change to Time GMT+7
ln -fs /usr/share/zoneinfo/Asia/Bangkok /etc/localtime


# About
clear
echo "Script by sakariya :-"
echo "-Pritunl"
echo "-Web Server"
echo "-Squid Proxy Port 8080"
echo "TimeZone   :  Bangkok"
echo "Pritunl    :  https://$MYIP"
echo "Login pritunl?"
echo "copy key"
pritunl setup-key
